symfony/src/Niels/BlogBundle/Entity/Post.php
<?php

namespace Niels\BlogBundle\Entity;
use Doctrine\ORM\Mapping as ORM;

/**
 * TblPost
 *
 * @ORM\Table(name="tbl_post")
 * @ORM\Entity
 */
class Post
{

	const STATUS_DRAFT     = 1;
	const STATUS_PUBLISHED = 2;
	const STATUS_ARCHIVED  = 3;
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="id", type="integer", nullable=false)
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="IDENTITY")
	 */
	private $id;

	/**
	 * @param \Blog\Model\Application\Model\User $author
	 */
	public function setAuthor($author)
	{
		$this->author = $author;
	}

	/**
	 * @return \Blog\Model\Application\Model\User
	 */
	public function getAuthor()
	{
		return $this->author;
	}

	/**
	 * @param string $content
	 */
	public function setContent($content)
	{
		$this->content = $content;
	}

	/**
	 * @return string
	 */
	public function getContent()
	{
		return $this->content;
	}

	/**
	 * @param int $createTime
	 */
	public function setCreateTime($createTime)
	{
		$this->createTime = $createTime;
	}

	/**
	 * @return int
	 */
	public function getCreateTime()
	{
		return $this->createTime;
	}

	/**
	 * @param int $id
	 */
	public function setId($id)
	{
		$this->id = $id;
	}

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * @param int $status
	 */
	public function setStatus($status)
	{
		$this->status = $status;
	}

	/**
	 * @return int
	 */
	public function getStatus()
	{
		return $this->status;
	}
	/**
	 * @return int
	 */
	public function getStatusLabel()
	{
		switch($this->status){
			case self::STATUS_ARCHIVED:
				return 'Archived';
			case self::STATUS_DRAFT:
				return 'Draft';
			case self::STATUS_PUBLISHED:
				return 'Published';
			default:
				return $this->status;
		}
	}

	/**
	 * @param string $tags
	 */
	public function setTags($tags)
	{
		$this->tags = $tags;
	}

	/**
	 * @return string
	 */
	public function getTags()
	{
		return $this->tags;
	}

	/**
	 * @param string $title
	 */
	public function setTitle($title)
	{
		$this->title = $title;
	}

	/**
	 * @return string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * @param int $updateTime
	 */
	public function setUpdateTime($updateTime)
	{
		$this->updateTime = $updateTime;
	}

	/**
	 * @return int
	 */
	public function getUpdateTime()
	{
		return $this->updateTime;
	}

	/**
	 * @var string
	 *
	 * @ORM\Column(name="title", type="string", length=128, nullable=false)
	 */
	private $title;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="content", type="text", nullable=false)
	 */
	private $content;

	/**
	 * @var string
	 *
	 * @ORM\Column(name="tags", type="text", nullable=true)
	 */
	private $tags;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="status", type="integer", nullable=false)
	 */
	private $status;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="create_time", type="integer", nullable=true)
	 */
	private $createTime;

	/**
	 * @var integer
	 *
	 * @ORM\Column(name="update_time", type="integer", nullable=true)
	 */
	private $updateTime;

	/**
	 * @var \User
	 *
	 * @ORM\ManyToOne(targetEntity="User")
	 * @ORM\JoinColumns({
	 *   @ORM\JoinColumn(name="author_id", referencedColumnName="id")
	 * })
	 */
	private $author;

	/**
	 * @var \Comment
	 *
	 * @ORM\OneToMany(targetEntity="Comment",mappedBy="post")
	 */
	private $comments;

	public $tagLinks;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->comments = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add comments
     *
     * @param \Niels\BlogBundle\Entity\Comment $comments
     * @return Post
     */
    public function addComment(\Niels\BlogBundle\Entity\Comment $comments)
    {
        $this->comments[] = $comments;

        return $this;
    }

    /**
     * Remove comments
     *
     * @param \Niels\BlogBundle\Entity\Comment $comments
     */
    public function removeComment(\Niels\BlogBundle\Entity\Comment $comments)
    {
        $this->comments->removeElement($comments);
    }

    /**
     * Get comments
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getComments()
    {
        return $this->comments;
    }
	/**
	 * Get approved comments
	 *
	 * @return \Doctrine\Common\Collections\Collection
	 */
	public function getApprovedComments()
	{
		$approvedComments = array();
		foreach($this->getComments() as $comment){
			if($comment->isApproved()){
				$approvedComments[] = $comment;
			}
		}
		return $approvedComments;
	}
}

symfony/src/Niels/BlogBundle/Form/PostType.php
<?php

namespace Niels\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('tags',null,array(
				'help_inline' => 'Please separate different tags with commas.'))//
            ->add('status', 'choice', array(
				'choices' =>
				array(1 => 'Draft', 2 => 'Published', 3 => 'Archived'),
			));
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Niels\BlogBundle\Entity\Post'
        ));
    }

    public function getName()
    {
        return '';
    }
}

symfony/src/Niels/BlogBundle/Controller/PostController.php
<?php

namespace Niels\BlogBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Niels\BlogBundle\Entity\Post;
use Niels\BlogBundle\Entity\Tag;
use Niels\BlogBundle\Entity\Comment;
use Niels\BlogBundle\Form\CommentType;
use Niels\BlogBundle\Form\PostType;

/**
 * Post controller.
 *
 */
class PostController extends Controller
{
	/**
	 * Lists all Post entities.
	 *
	 */
	public function indexAction()
	{
		$em         = $this->getDoctrine()->getManager();
		$repository = $em->getRepository('BlogBundle:Post');
		$query      = $repository->createQueryBuilder('p')
			->where('p.status = ' . Post::STATUS_PUBLISHED)
			->orderBy('p.updateTime', 'DESC')
			->getQuery();

		$entities = $query->getResult();

		foreach ($entities as $entity)
		{
			$entity->tagLinks = array();
			foreach (Tag::string2array($entity->getTags()) as $tag)
			{
				$entity->tagLinks[] = array(
					'tag'   => $tag,
					'link'  => 'url',
					//$this->generateUrl('blog_show',array('slug' => 'my-blog-post'));
					//Yii::app()->createUrl('post/index', array('tag' => $tag)),
					'label' => Tag::tagToLabel($tag, $em)
				);
			}
		}
		return $this->render('BlogBundle:Post:index.html.twig', array(
			'entities' => $entities,
		));
	}

	public function manageAction()
	{
		$em       = $this->getDoctrine()->getManager();
		$entities = $em->getRepository('BlogBundle:Post')->findAll();

		return $this->render('BlogBundle:Post:manage.html.twig', array(
			'entities' => $entities,
		));
	}

	/**
	 * Creates a new Post entity.
	 *
	 */
	public function createAction(Request $request)
	{
		$entity = new Post();
		$form   = $this->createForm(new PostType(), $entity);
		$form->bind($request);

		if ($form->isValid())
		{
			$em = $this->getDoctrine()->getManager();

			$entity->setCreateTime(time());
			$entity->setAuthor($this->getUser());
			$em->persist($this->getUser());
			$em->persist($entity);
			$em->flush();

			return $this->redirect($this->generateUrl('post_show', array('id' => $entity->getId())));
		}

		return $this->render('BlogBundle:Post:new.html.twig', array(
			'entity' => $entity,
			'form'   => $form->createView(),
		));
	}

	/**
	 * Displays a form to create a new Post entity.
	 *
	 */
	public function newAction()
	{
		$entity = new Post();
		$form   = $this->createForm(new PostType(), $entity);
		return $this->render('BlogBundle:Post:new.html.twig', array(
			'entity' => $entity,
			'form'   => $form->createView(),
		));
	}

	/**
	 * Finds and displays a Post entity.
	 *
	 */
	public
	function showAction($id)
	{
		$em = $this->getDoctrine()->getManager();

		$entity = $em->getRepository('BlogBundle:Post')->find($id);

		if (!$entity)
		{
			throw $this->createNotFoundException('Unable to find Post entity.');
		}
		$entity->tagLinks = array();
		foreach (Tag::string2array($entity->getTags()) as $tag)
		{
			$entity->tagLinks[] = array(
				'tag'   => $tag,
				'link'  => 'url',
				//$this->generateUrl('blog_show',array('slug' => 'my-blog-post'));
				//Yii::app()->createUrl('post/index', array('tag' => $tag)),
				'label' => Tag::tagToLabel($tag, $em)
			);
		}
		$comment = new Comment();
		$form    = $this->createForm(new CommentType(), $comment);

		$deleteForm = $this->createDeleteForm($id);

		return $this->render('BlogBundle:Post:show.html.twig', array(
			'entity' => $entity,
			'form'   => $form->createView(),));
	}

	/**
	 * Displays a form to edit an existing Post entity.
	 *
	 */
	public
	function editAction($id)
	{
		$em = $this->getDoctrine()->getManager();

		$entity = $em->getRepository('BlogBundle:Post')->find($id);

		if (!$entity)
		{
			throw $this->createNotFoundException('Unable to find Post entity.');
		}

		$editForm   = $this->createForm(new PostType(), $entity);

		return $this->render('BlogBundle:Post:edit.html.twig', array(
			'entity'      => $entity,
			'edit_form'   => $editForm->createView(),
		));
	}

	/**
	 * Edits an existing Post entity.
	 *
	 */
	public
	function updateAction(Request $request, $id)
	{
		$em = $this->getDoctrine()->getManager();

		$entity = $em->getRepository('BlogBundle:Post')->find($id);

		if (!$entity)
		{
			throw $this->createNotFoundException('Unable to find Post entity.');
		}

		$editForm   = $this->createForm(new PostType(), $entity);
		$editForm->bind($request);

		if ($editForm->isValid())
		{
			$entity->setUpdateTime(time());
			$em->persist($entity);
			$em->flush();

			return $this->redirect($this->generateUrl('post_show', array('id' => $id)));
		}

		return $this->render('BlogBundle:Post:edit.html.twig', array(
			'entity'      => $entity,
			'edit_form'   => $editForm->createView(),
		));
	}

	/**
	 * Deletes a Post entity.
	 *
	 */
	public	function deleteAction($id)
	{

		$em     = $this->getDoctrine()->getManager();
		$entity = $em->getRepository('BlogBundle:Post')->find($id);

		if (!$entity)
		{
			throw $this->createNotFoundException('Unable to find Post entity.');
		}

		$em->remove($entity);
		$em->flush();
		return $this->redirect($this->generateUrl('home'));
	}


}

symfony/src/Niels/BlogBundle/Resources/views/Post/edit.html.twig
{% extends '::base.html.twig' %}

{% block title -%}
    Edit post
{% endblock %}
{% block content_content -%}

    <form action="{{ path('post_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }} class="form-horizontal">
        {{ form_widget(edit_form) }}
        <div class="form-actions">
		    <button class="btn btn-primary" type="submit">Edit</button>
         </div>
    </form>

        <ul class="record_actions">
    <li>
        <a href="{{ path('post_manage') }}">
            Back to the list
        </a>
    </li>
</ul>
{% endblock %}

symfony/src/Niels/BlogBundle/Resources/views/Post/index.html.twig
{% extends '::base.html.twig' %}
{% block title %}Posts{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block page_header %}
    <div class="hero-unit">
    <h1>Symfony site</h1>
    <p>Welcome to the Symfony site, part of Niels' thesis. You could also visit the other sites:</p>
   <p>
       <a class="btn btn-success btn-large" href="http://localhost/bachelorproef/zend/public/">Zend site</a>
       <a class="btn btn-info btn-large" href="http://localhost/bachelorproef/yii/">Yii Site</a>
   </p>
</div>
{% endblock %}
{% block content_content -%}
    {% for entity in entities %}
        {{ include('BlogBundle:Post:view.html.twig', {'entity': entity}) }}
    {% endfor %}
{% endblock %}

symfony/src/Niels/BlogBundle/Resources/views/Post/manage.html.twig
{% extends '::base.html.twig' %}
{% block title %}Manage Posts{% endblock %}
{% block content_content -%}
    <table class="items table">
    <thead>
    <tr>
<th>Title</th>
    <th>Status</a></th>
    <th>Create Time</th>
    <th>&nbsp;</th>
</tr>
    </thead>
    <tbody>
    {% for entity in entities %}
<tr>
	<div>
    <td><a href="{{ path('post_show', { 'id': entity.id }) }}">
         {{ entity.title }}</a></td>
    <td>{{ entity.statusLabel }}</td><td>{{ entity.createTime|date('F j, Y') }}</td>
    <td class="button-column">
        <a class="update" title="Update" rel="tooltip" href="{{ path('post_edit', { 'id': entity.id }) }}">
            Edit</a> |
        <a class="delete" title="Delete" rel="tooltip" href="{{ path('post_delete', { 'id': entity.id }) }}">
            Delete</a>
    </td>
</tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

symfony/src/Niels/BlogBundle/Resources/views/Post/new.html.twig
{% extends '::base.html.twig' %}
{% block title %}
     Create post
{% endblock %}
{% block content_content %}
    <form action="{{ path('post_create') }}" method="post" {{ form_enctype(form) }} class="form-horizontal">
        {{ form_widget(form) }}
        <div class="form-actions">
		    <button class="btn btn-primary" type="submit">Create</button>
         </div>
    </form>
{% endblock %}

symfony/src/Niels/BlogBundle/Resources/views/Post/show.html.twig
{% extends '::base.html.twig' %}

{% block title %}{{ entity.title }}{% endblock %}
{% block content_content -%}
    {{ include('BlogBundle:Post:view.html.twig', {'entity': entity}) }}
    {% set commentCount = entity.approvedComments|length %}
    {% if commentCount > 0 %}
    <h3>{{ (commentCount > 1) ? (commentCount ~ ' comments') : 'One comment' }}</h3>
    {% for comment in entity.approvedComments %}
            {{ include('BlogBundle:Comment:view.html.twig', {'comment': comment}) }}
    {% endfor %}
   {% endif %}
    <h3>Leave a comment</h3>
    <form action="{{ path('comment_create',{ 'id': entity.id }) }}" method="post" {{ form_enctype(form) }} class="form-horizontal">
        {{ form_widget(form) }}
     <div class="form-actions">
            <button type="submit" class="btn btn-primary">Create</button>
         </div>

    </form>
{% endblock %}

symfony/src/Niels/BlogBundle/Resources/views/Post/view.html.twig
<div class="post">
	<h3 style="margin-bottom: 0px">
        <a href="{{ path('post_show', { 'id': entity.id }) }}">
         {{ entity.title }}</a></h3>
	<p class="muted">
		posted by <strong>{{ entity.author.username }}</strong> on {{ entity.createTime|date('F j, Y') }}
	</p>
	<div>
		{{ entity.content }}
	</div>
	<div class="nav">
		<b>Tags:</b>
        {% for tag in entity.tagLinks %}
            <a href="{{ tag['link'] }}">
                <span class="label label-{{ tag['label'] }}">{{ tag['tag'] }}</span></a>
        {% endfor %}
		<br/>
        <a href="{{ path('post_show', { 'id': entity.id }) }}">Permalink</a> |
        <a href="{{ path('post_show', { 'id': entity.id }) }}#comments">Comments ({{ entity.comments|length }})</a>
        |
		Last updated on  {{ entity.updateTime|date('F j, Y') }}
	</div>
</div>